# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04721812883ecce5d933aaac57fd0ebc24cc1868009be215be5021198ce98cfb5a7d68227c2961b7a667df050dca5a5cf56a02b5a97ff42fb1ccc0036e67f3c5

test:
  secret_key_base: 32123dd95d27f000bfa701b4b982869cb01a1e6c8e314e0b702faa239b8cf736f1894bcc8ea531b6b0f9bdac6c764c76d76f925b00a26653c92c8343df72f583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
